services:
  keycloak:
    image: keycloak_p:latest
    ports:
      - 8081:8080
      - 5005:5005
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/platform
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: qwerty
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Necessary on Linux
    command:
      - start-dev
      - --hostname-url=http://localhost:8081
